// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Booking is the struct bound to Wails (registered as a v3 service). It owns the
 * application-level concerns (field schema, window, settings, Excel/dialog I/O)
 * and delegates all table state and operations to doc.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportToExcel saves the current rows to an xlsx file chosen via save dialog.
 * It returns true when a file was written, false when the user cancelled.
 */
export function ExportToExcel(): $CancellablePromise<boolean> {
    return $Call.ByID(3324198873);
}

/**
 * GetCharMapping returns the current unicode→replacement substitution map.
 */
export function GetCharMapping(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2187065419).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFields returns the current field definitions for the Mezők tab.
 */
export function GetFields(): $CancellablePromise<$models.Field[]> {
    return $Call.ByID(2340982902).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRecentFiles returns the most-recently-opened file paths (newest first).
 */
export function GetRecentFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(674861675).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetServicePrices returns the current service → net-unit-price lookup.
 */
export function GetServicePrices(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1560283408).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSettings returns the current user settings (called on frontend mount).
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2598443442).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetStatus returns the currently open Excel file path for the status bar.
 */
export function GetStatus(): $CancellablePromise<string> {
    return $Call.ByID(3547302729);
}

/**
 * GetTableData returns the current in-memory table.
 */
export function GetTableData(): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(1643564193).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ImportFromExcel loads rows from a previously exported xlsx file.
 */
export function ImportFromExcel(): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(757548863).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadRecentFile reopens a previously used file without a dialog and returns its
 * sheet names. A missing file is dropped from the recent list and reported.
 */
export function LoadRecentFile(path: string): $CancellablePromise<string[]> {
    return $Call.ByID(1000020668, path).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * LoadSheet reads the named sheet from the already-opened Excel file.
 */
export function LoadSheet(sheetName: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(2750288452, sheetName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenBookedFile shows a file-open dialog for xlsx files and returns the sheet names.
 */
export function OpenBookedFile(): $CancellablePromise<string[]> {
    return $Call.ByID(2313661635).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PreviewCSV renders the CSV exactly as SaveCSV would (char mapping applied) but
 * returns it as a UTF-8 string for on-screen display, regardless of the export
 * encoding.
 */
export function PreviewCSV(): $CancellablePromise<string> {
    return $Call.ByID(2614661465);
}

/**
 * ReapplyFields re-applies current editable/const/date field values to all non-MAPPING rows.
 */
export function ReapplyFields(): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(2317909817).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveCSV writes the Számlázz.hu CSV using the encoding from settings.
 * SaveCSV returns true when a file was written, false when the user cancelled
 * the dialog (so the frontend can skip the success notification).
 */
export function SaveCSV(): $CancellablePromise<boolean> {
    return $Call.ByID(2381375736);
}

/**
 * SetAllRowsEnabled toggles every row on or off (select-all / select-none).
 */
export function SetAllRowsEnabled(enabled: boolean): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(4222319800, enabled).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetCharMapping replaces the substitution map, re-validates all cells, saves settings.
 */
export function SetCharMapping(m: { [_ in string]?: string }): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3012984231, m).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetColorScheme persists the UI color scheme ("light" | "dark" | "auto").
 */
export function SetColorScheme(scheme: string): $CancellablePromise<void> {
    return $Call.ByID(532239465, scheme);
}

/**
 * SetEncoding updates the CSV encoding, re-validates all cells, persists the
 * choice, and returns the new table state.
 */
export function SetEncoding(enc: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3543820506, enc).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetRowEnabled toggles whether a single row is included in CSV export.
 */
export function SetRowEnabled(rowIndex: number, enabled: boolean): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3711206202, rowIndex, enabled).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetServicePrices replaces the price lookup, re-applies it to all rows,
 * re-validates, and saves settings.
 */
export function SetServicePrices(m: { [_ in string]?: string }): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3348534596, m).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateCell mutates one cell and re-validates it in place.
 */
export function UpdateCell(rowIndex: number, colName: string, value: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(2945283456, rowIndex, colName, value).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateFieldValue mutates the in-memory value of an editable field.
 */
export function UpdateFieldValue(fieldName: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2688728897, fieldName, value);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.Field.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.Settings.createFrom;
const $$createType5 = $models.TableDataResult.createFrom;
