// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Booking is the struct bound to Wails (registered as a v3 service). It owns the
 * application-level concerns (field schema, window, settings, Excel/dialog I/O)
 * and delegates all table state and operations to doc.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyFieldToRows overwrites the named field's column across loaded rows and
 * re-validates. mode "all" rewrites every row; mode "match" rewrites only rows whose
 * current cell still equals prevValue — i.e. rows untouched since the old default,
 * leaving manually-edited rows alone (a stateless proxy: a row hand-edited back to the
 * old default is treated as untouched, which is acceptable). Unlike ReapplyFields
 * (which rewrites every non-MAPPING column), this is deliberately narrow: the UI
 * applies one field at a time so a field the user chose to leave is never clobbered.
 * MAPPING fields (read from the source sheet) and unknown names are no-ops.
 */
export function ApplyFieldToRows(fieldName: string, mode: string, prevValue: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(1799160833, fieldName, mode, prevValue).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportToExcel saves the current rows to an xlsx file chosen via save dialog.
 * It returns true when a file was written, false when the user cancelled.
 */
export function ExportToExcel(): $CancellablePromise<boolean> {
    return $Call.ByID(3324198873);
}

/**
 * GetCharMapping returns the current unicode→replacement substitution map.
 */
export function GetCharMapping(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2187065419).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetColumnRoles returns the role→name mapping the frontend needs to locate the
 * service, price and partner columns without hardcoding their names (called on
 * mount). Partner lets the UI name the customer behind a problem row.
 */
export function GetColumnRoles(): $CancellablePromise<$models.ColumnRoles> {
    return $Call.ByID(2740252054).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetFields returns the current field definitions for the Mezők tab.
 */
export function GetFields(): $CancellablePromise<$models.Field[]> {
    return $Call.ByID(2340982902).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRecentFiles returns the most-recently-opened file paths (newest first).
 */
export function GetRecentFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(674861675).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetServicePrices returns the current service → net-unit-price lookup.
 */
export function GetServicePrices(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1560283408).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSettings returns the UI-relevant subset of user settings (called on
 * frontend mount).
 */
export function GetSettings(): $CancellablePromise<$models.UISettings> {
    return $Call.ByID(2598443442).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetStatus returns the currently open Excel file path for the status bar.
 */
export function GetStatus(): $CancellablePromise<string> {
    return $Call.ByID(3547302729);
}

/**
 * GetTableData returns the current in-memory table.
 */
export function GetTableData(): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(1643564193).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromExcel loads rows from a previously exported xlsx file.
 */
export function ImportFromExcel(): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(757548863).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LoadRecentFile reopens a previously used file without a dialog and returns its
 * sheet names. A missing file is dropped from the recent list and reported.
 */
export function LoadRecentFile(path: string): $CancellablePromise<string[]> {
    return $Call.ByID(1000020668, path).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadSheet reads the named sheet from the already-opened Excel file.
 */
export function LoadSheet(sheetName: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(2750288452, sheetName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenBookedFile shows a file-open dialog for xlsx files and returns the sheet names.
 */
export function OpenBookedFile(): $CancellablePromise<string[]> {
    return $Call.ByID(2313661635).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * PreviewCSV renders the CSV exactly as SaveCSV would (char mapping applied) but
 * returns it as a UTF-8 string for on-screen display, regardless of the export
 * encoding.
 */
export function PreviewCSV(): $CancellablePromise<string> {
    return $Call.ByID(2614661465);
}

/**
 * ReapplyFields re-applies current editable/const/date field values to all non-MAPPING rows.
 */
export function ReapplyFields(): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(2317909817).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveCSV writes the Számlázz.hu CSV using the encoding from settings.
 * SaveCSV returns true when a file was written, false when the user cancelled
 * the dialog (so the frontend can skip the success notification).
 */
export function SaveCSV(): $CancellablePromise<boolean> {
    return $Call.ByID(2381375736);
}

/**
 * SetAllRowsEnabled toggles every row on or off (select-all / select-none).
 */
export function SetAllRowsEnabled(enabled: boolean): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(4222319800, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApplyMode persists how a field-default change propagates to already-loaded
 * rows: "never" (leave rows), "match" (only rows still on the old default),
 * "ask" (prompt each time), or "always" (rewrite every row).
 */
export function SetApplyMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3677944730, mode);
}

/**
 * SetCharMapping replaces the substitution map, re-validates all cells, saves settings.
 */
export function SetCharMapping(m: { [_ in string]?: string }): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3012984231, m).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetColorScheme persists the UI color scheme ("light" | "dark" | "auto").
 */
export function SetColorScheme(scheme: string): $CancellablePromise<void> {
    return $Call.ByID(532239465, scheme);
}

/**
 * SetEncoding updates the CSV encoding, re-validates all cells, persists the
 * choice, and returns the new table state.
 */
export function SetEncoding(enc: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3543820506, enc).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetRowEnabled toggles whether a single row is included in CSV export.
 */
export function SetRowEnabled(rowIndex: number, enabled: boolean): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3711206202, rowIndex, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetServicePrices replaces the price lookup (always persisted) and pushes the change
 * onto already-loaded rows according to mode — mirroring the field-default workflow:
 *   - "never": leave loaded rows as they are (only the lookup changes)
 *   - "match": rewrite only rows whose price cell still equals the service's previous
 *     effective price (untouched rows), leaving hand-edited rows alone
 *   - "all" (default): rewrite every row whose service has a configured price
 * 
 * The "ask" mode is resolved to one of the above by the frontend before calling. Rows
 * are always re-validated so unpriced-service warnings clear as soon as a price exists,
 * even in "never" mode where the cells themselves are untouched.
 */
export function SetServicePrices(m: { [_ in string]?: string }, mode: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(3348534596, m, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateCell mutates one cell and re-validates it in place.
 */
export function UpdateCell(rowIndex: number, colName: string, value: string): $CancellablePromise<$models.TableDataResult> {
    return $Call.ByID(2945283456, rowIndex, colName, value).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateFieldValue mutates the in-memory value of an editable field.
 */
export function UpdateFieldValue(fieldName: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2688728897, fieldName, value);
}

// Private type creation functions
const $$createType0 = $models.TableDataResult.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.ColumnRoles.createFrom;
const $$createType3 = $models.Field.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.UISettings.createFrom;
