// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CellError describes one cell whose value cannot be encoded in the current encoding.
 */
export class CellError {
    "rowIndex": number;
    "colName": string;
    "value": string;
    "invalidChar": string;
    "charPos": number;

    /**
     * true → substitution exists (yellow); false → blocked (red)
     */
    "mapped": boolean;

    /**
     * replacement string when Mapped==true
     */
    "mappedTo": string;

    /**
     * "error" (red) | "mapped" (yellow) | "warning" (orange)
     */
    "severity": string;

    /**
     * human-readable description for tooltip / status bar
     */
    "message": string;

    /** Creates a new CellError instance. */
    constructor($$source: Partial<CellError> = {}) {
        if (!("rowIndex" in $$source)) {
            this["rowIndex"] = 0;
        }
        if (!("colName" in $$source)) {
            this["colName"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("invalidChar" in $$source)) {
            this["invalidChar"] = "";
        }
        if (!("charPos" in $$source)) {
            this["charPos"] = 0;
        }
        if (!("mapped" in $$source)) {
            this["mapped"] = false;
        }
        if (!("mappedTo" in $$source)) {
            this["mappedTo"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellError instance from a string or object.
     */
    static createFrom($$source: any = {}): CellError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CellError($$parsedSource as Partial<CellError>);
    }
}

/**
 * ColumnRoles names the output columns the frontend must identify by role — the
 * service/item column and the net-unit-price column. The backend owns the schema,
 * so the UI reads these instead of re-typing the Hungarian literals (which would
 * be a third place the names live, alongside these consts and fields.yaml).
 */
export class ColumnRoles {
    "service": string;
    "price": string;

    /** Creates a new ColumnRoles instance. */
    constructor($$source: Partial<ColumnRoles> = {}) {
        if (!("service" in $$source)) {
            this["service"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnRoles instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnRoles {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnRoles($$parsedSource as Partial<ColumnRoles>);
    }
}

/**
 * Field is serialised to JSON and sent to the frontend for the Mezők tab.
 */
export class Field {
    "name": string;
    "type": FieldType;
    "mapping"?: string;
    "value": string;
    "options"?: string[];

    /** Creates a new Field instance. */
    constructor($$source: Partial<Field> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = FieldType.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Field instance from a string or object.
     */
    static createFrom($$source: any = {}): Field {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new Field($$parsedSource as Partial<Field>);
    }
}

/**
 * FieldType distinguishes how a column's value is sourced.
 */
export enum FieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FieldTypeMapping = "MAPPING",
    FieldTypeConst = "CONST",
    FieldTypeText = "TEXT",
    FieldTypeDate = "DATE",
};

/**
 * TableDataResult is returned to the frontend whenever the table changes.
 */
export class TableDataResult {
    "columns": string[];
    "rows": string[][];
    "rowEnabled": boolean[];
    "cellErrors": CellError[];

    /** Creates a new TableDataResult instance. */
    constructor($$source: Partial<TableDataResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowEnabled" in $$source)) {
            this["rowEnabled"] = [];
        }
        if (!("cellErrors" in $$source)) {
            this["cellErrors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDataResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TableDataResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("rowEnabled" in $$parsedSource) {
            $$parsedSource["rowEnabled"] = $$createField2_0($$parsedSource["rowEnabled"]);
        }
        if ("cellErrors" in $$parsedSource) {
            $$parsedSource["cellErrors"] = $$createField3_0($$parsedSource["cellErrors"]);
        }
        return new TableDataResult($$parsedSource as Partial<TableDataResult>);
    }
}

/**
 * UISettings is the subset of Settings the frontend hydrates from on mount
 * (GetSettings). Window geometry and persisted field values are backend-managed
 * and deliberately excluded — the frontend never reads them, so the bound API
 * surfaces exactly what the UI consumes.
 */
export class UISettings {
    "colorScheme": string;
    "encoding": string;
    "charMapping": { [_ in string]?: string };
    "servicePrices": { [_ in string]?: string };
    "recentFiles": string[];

    /** Creates a new UISettings instance. */
    constructor($$source: Partial<UISettings> = {}) {
        if (!("colorScheme" in $$source)) {
            this["colorScheme"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("charMapping" in $$source)) {
            this["charMapping"] = {};
        }
        if (!("servicePrices" in $$source)) {
            this["servicePrices"] = {};
        }
        if (!("recentFiles" in $$source)) {
            this["recentFiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UISettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UISettings {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("charMapping" in $$parsedSource) {
            $$parsedSource["charMapping"] = $$createField2_0($$parsedSource["charMapping"]);
        }
        if ("servicePrices" in $$parsedSource) {
            $$parsedSource["servicePrices"] = $$createField3_0($$parsedSource["servicePrices"]);
        }
        if ("recentFiles" in $$parsedSource) {
            $$parsedSource["recentFiles"] = $$createField4_0($$parsedSource["recentFiles"]);
        }
        return new UISettings($$parsedSource as Partial<UISettings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CellError.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
