// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CellError describes one cell whose value cannot be encoded in the current encoding.
 */
export class CellError {
    "rowIndex": number;
    "colName": string;
    "value": string;
    "invalidChar": string;
    "charPos": number;

    /**
     * true → substitution exists (yellow); false → blocked (red)
     */
    "mapped": boolean;

    /**
     * replacement string when Mapped==true
     */
    "mappedTo": string;

    /**
     * "error" (red) | "mapped" (yellow) | "warning" (orange)
     */
    "severity": string;

    /**
     * human-readable description for tooltip / status bar
     */
    "message": string;

    /** Creates a new CellError instance. */
    constructor($$source: Partial<CellError> = {}) {
        if (!("rowIndex" in $$source)) {
            this["rowIndex"] = 0;
        }
        if (!("colName" in $$source)) {
            this["colName"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("invalidChar" in $$source)) {
            this["invalidChar"] = "";
        }
        if (!("charPos" in $$source)) {
            this["charPos"] = 0;
        }
        if (!("mapped" in $$source)) {
            this["mapped"] = false;
        }
        if (!("mappedTo" in $$source)) {
            this["mappedTo"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellError instance from a string or object.
     */
    static createFrom($$source: any = {}): CellError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CellError($$parsedSource as Partial<CellError>);
    }
}

/**
 * Field is serialised to JSON and sent to the frontend for the Mezők tab.
 */
export class Field {
    "name": string;
    "type": FieldType;
    "mapping"?: string;
    "value": string;
    "options"?: string[];

    /** Creates a new Field instance. */
    constructor($$source: Partial<Field> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = FieldType.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Field instance from a string or object.
     */
    static createFrom($$source: any = {}): Field {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new Field($$parsedSource as Partial<Field>);
    }
}

/**
 * FieldType distinguishes how a column's value is sourced.
 */
export enum FieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FieldTypeMapping = "MAPPING",
    FieldTypeConst = "CONST",
    FieldTypeText = "TEXT",
    FieldTypeDate = "DATE",
};

/**
 * Settings holds user preferences persisted across sessions.
 */
export class Settings {
    /**
     * "light" | "dark" | "auto"
     */
    "colorScheme": string;

    /**
     * "ISO-8859-2" | "UTF-8"
     */
    "encoding": string;

    /**
     * unicode char → latin-2 replacement
     */
    "charMapping": { [_ in string]?: string };

    /**
     * persisted TEXT editable field values
     */
    "fieldValues": { [_ in string]?: string };

    /**
     * service name → net unit price
     */
    "servicePrices": { [_ in string]?: string };

    /**
     * most-recent-first, capped
     */
    "recentFiles": string[];
    "windowX": number;
    "windowY": number;
    "windowW": number;
    "windowH": number;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("colorScheme" in $$source)) {
            this["colorScheme"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("charMapping" in $$source)) {
            this["charMapping"] = {};
        }
        if (!("fieldValues" in $$source)) {
            this["fieldValues"] = {};
        }
        if (!("servicePrices" in $$source)) {
            this["servicePrices"] = {};
        }
        if (!("recentFiles" in $$source)) {
            this["recentFiles"] = [];
        }
        if (!("windowX" in $$source)) {
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            this["windowY"] = 0;
        }
        if (!("windowW" in $$source)) {
            this["windowW"] = 0;
        }
        if (!("windowH" in $$source)) {
            this["windowH"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("charMapping" in $$parsedSource) {
            $$parsedSource["charMapping"] = $$createField2_0($$parsedSource["charMapping"]);
        }
        if ("fieldValues" in $$parsedSource) {
            $$parsedSource["fieldValues"] = $$createField3_0($$parsedSource["fieldValues"]);
        }
        if ("servicePrices" in $$parsedSource) {
            $$parsedSource["servicePrices"] = $$createField4_0($$parsedSource["servicePrices"]);
        }
        if ("recentFiles" in $$parsedSource) {
            $$parsedSource["recentFiles"] = $$createField5_0($$parsedSource["recentFiles"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * TableDataResult is returned to the frontend whenever the table changes.
 */
export class TableDataResult {
    "columns": string[];
    "rows": string[][];
    "rowEnabled": boolean[];
    "cellErrors": CellError[];

    /** Creates a new TableDataResult instance. */
    constructor($$source: Partial<TableDataResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowEnabled" in $$source)) {
            this["rowEnabled"] = [];
        }
        if (!("cellErrors" in $$source)) {
            this["cellErrors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDataResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TableDataResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("rowEnabled" in $$parsedSource) {
            $$parsedSource["rowEnabled"] = $$createField2_0($$parsedSource["rowEnabled"]);
        }
        if ("cellErrors" in $$parsedSource) {
            $$parsedSource["cellErrors"] = $$createField3_0($$parsedSource["cellErrors"]);
        }
        return new TableDataResult($$parsedSource as Partial<TableDataResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = CellError.createFrom;
const $$createType5 = $Create.Array($$createType4);
