// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToExcel() {
  return window['go']['main']['Booking']['ExportToExcel']();
}

export function GetCharMapping() {
  return window['go']['main']['Booking']['GetCharMapping']();
}

export function GetFields() {
  return window['go']['main']['Booking']['GetFields']();
}

export function GetRecentFiles() {
  return window['go']['main']['Booking']['GetRecentFiles']();
}

export function GetServicePrices() {
  return window['go']['main']['Booking']['GetServicePrices']();
}

export function GetSettings() {
  return window['go']['main']['Booking']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['Booking']['GetStatus']();
}

export function GetTableData() {
  return window['go']['main']['Booking']['GetTableData']();
}

export function ImportFromExcel() {
  return window['go']['main']['Booking']['ImportFromExcel']();
}

export function LoadRecentFile(arg1) {
  return window['go']['main']['Booking']['LoadRecentFile'](arg1);
}

export function LoadSheet(arg1) {
  return window['go']['main']['Booking']['LoadSheet'](arg1);
}

export function OpenBookedFile() {
  return window['go']['main']['Booking']['OpenBookedFile']();
}

export function PreviewCSV() {
  return window['go']['main']['Booking']['PreviewCSV']();
}

export function ReapplyFields() {
  return window['go']['main']['Booking']['ReapplyFields']();
}

export function SaveCSV() {
  return window['go']['main']['Booking']['SaveCSV']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['Booking']['SaveSettings'](arg1);
}

export function SetCharMapping(arg1) {
  return window['go']['main']['Booking']['SetCharMapping'](arg1);
}

export function SetColorScheme(arg1) {
  return window['go']['main']['Booking']['SetColorScheme'](arg1);
}

export function SetEncoding(arg1) {
  return window['go']['main']['Booking']['SetEncoding'](arg1);
}

export function SetServicePrices(arg1) {
  return window['go']['main']['Booking']['SetServicePrices'](arg1);
}

export function UpdateCell(arg1, arg2, arg3) {
  return window['go']['main']['Booking']['UpdateCell'](arg1, arg2, arg3);
}

export function UpdateFieldValue(arg1, arg2) {
  return window['go']['main']['Booking']['UpdateFieldValue'](arg1, arg2);
}
