// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToExcel() {
  return window['go']['main']['Booking']['ExportToExcel']();
}

export function GetFields() {
  return window['go']['main']['Booking']['GetFields']();
}

export function GetStatus() {
  return window['go']['main']['Booking']['GetStatus']();
}

export function GetTableData() {
  return window['go']['main']['Booking']['GetTableData']();
}

export function ImportFromExcel() {
  return window['go']['main']['Booking']['ImportFromExcel']();
}

export function LoadSheet(arg1) {
  return window['go']['main']['Booking']['LoadSheet'](arg1);
}

export function OpenBookedFile() {
  return window['go']['main']['Booking']['OpenBookedFile']();
}

export function ReapplyFields() {
  return window['go']['main']['Booking']['ReapplyFields']();
}

export function SaveCSV(arg1) {
  return window['go']['main']['Booking']['SaveCSV'](arg1);
}

export function UpdateCell(arg1, arg2, arg3) {
  return window['go']['main']['Booking']['UpdateCell'](arg1, arg2, arg3);
}

export function UpdateFieldValue(arg1, arg2) {
  return window['go']['main']['Booking']['UpdateFieldValue'](arg1, arg2);
}
