// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportToExcel():Promise<void>;

export function GetFields():Promise<Array<main.Field>>;

export function GetStatus():Promise<string>;

export function GetTableData():Promise<main.TableDataResult>;

export function ImportFromExcel():Promise<main.TableDataResult>;

export function LoadSheet(arg1:string):Promise<main.TableDataResult>;

export function OpenBookedFile():Promise<Array<string>>;

export function ReapplyFields():Promise<main.TableDataResult>;

export function SaveCSV(arg1:string):Promise<void>;

export function UpdateCell(arg1:number,arg2:string,arg3:string):Promise<main.TableDataResult>;

export function UpdateFieldValue(arg1:string,arg2:string):Promise<void>;
