// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportToExcel():Promise<void>;

export function GetCharMapping():Promise<Record<string, string>>;

export function GetFields():Promise<Array<main.Field>>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<string>;

export function GetTableData():Promise<main.TableDataResult>;

export function ImportFromExcel():Promise<main.TableDataResult>;

export function LoadSheet(arg1:string):Promise<main.TableDataResult>;

export function OpenBookedFile():Promise<Array<string>>;

export function ReapplyFields():Promise<main.TableDataResult>;

export function SaveCSV():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetCharMapping(arg1:Record<string, string>):Promise<main.TableDataResult>;

export function SetEncoding(arg1:string):Promise<main.TableDataResult>;

export function UpdateCell(arg1:number,arg2:string,arg3:string):Promise<main.TableDataResult>;

export function UpdateFieldValue(arg1:string,arg2:string):Promise<void>;
